# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  title: 中国科大 AGI 研究组
  params:
    description: 中国科学技术大学 AGI 研究组关注智能体智能、大模型、数据挖掘、时间序列分析、表格推理、推荐系统与 AI for Science。

# Uncomment the lines below to configure your website in a second language.
#en:
#  languageCode: en-us
#  contentDir: content/en
#  title: English website title...
#  params:
#    description: Site description in English...
#  menu:
#    main:
#      - name: About
#        url: '#about'
#        weight: 1
