# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  title: USTC-AGI Research Group
  params:
    description: 以机器学习与数据挖掘为根基，以深度神经网络、大模型推理与智能体、情境大数据智能为核心技术，面向科学智能、时序智能与推荐系统开展基础方法与关键应用研究。

# Uncomment the lines below to configure your website in a second language.
#en:
#  languageCode: en-us
#  contentDir: content/en
#  title: English website title...
#  params:
#    description: Site description in English...
#  menu:
#    main:
#      - name: About
#        url: '#about'
#        weight: 1
