# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 动态发布
    url: post
    weight: 10
  - name: 师生成员
    url: people
    weight: 20
  - name: 研究方向
    url: research
    weight: 30
  - name: 论文列表
    url: publication
    weight: 40
  - name: 开源项目
    url: open-source
    weight: 50
  - name: 系统
    url: project
    weight: 60
  - name: 代码仓库
    url: https://github.com/USTCAGI
    weight: 70
