# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: 
  # font:
  font_size: M

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: '中国科大 AGI 研究组'
    description: '中国科学技术大学 AGI 研究组关注智能体智能、大模型、数据挖掘、时间序列分析、表格推理、推荐系统与 AI for Science。'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

# Site footer

footer:
  text: 安徽省合肥市高新技术产业开发区复兴路100号 中国科学技术大学（高新校区）
  copyright:
    notice: '© {year} AGI Group'

# Localization

locale:
  date_format: '2006年1月2日'
  time_format: '3:04 PM'
  address_format: zh-cn

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/USTCAGI/USTCAGI.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: 2006年1月
  citation_style: apa
